# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: uah_temps_development
  pool: 5
#  username: sample_postgres
#  password:

test:
  adapter: postgresql
  encoding: unicode
  database: uah_temps_test
  pool: 5
#  username: sample_postgres
#  password:

production:
  adapter: postgresql
  encoding: unicode
  database: uah_temps_production
  pool: 5
#  username: sample_postgres
#  password:
